### ISSUE TITLE
Unable to duplicate scripts on one store "Failed to duplicate the script" error message

### ISSUE THREAD

**Issue by Rony-C** [Shopify/shopify-scripts#11]
### Problem

Unable to duplicate scripts on store, getting "Failed to duplicate the script" error message. Showing 422 error in Console

### Scope

[One store](https://app.shopify.com/services/internal/shops/5434293)

### Examples

* [Merchants store](https://app.shopify.com/services/internal/shops/5434293)
* [Example script](https://shopatshowcase.myshopify.com/admin/apps/d25e45407e508f96409c2dd796e9bd95/scripts/24019051)
* [Video of issue](https://screenshot.click/qrhze_2019-08-06.mp4)

#### Expected vs Actual

**EB:** Duplicating a script will create a duplicate

**AB:** Duplicating a script will result in an error message & 422 error

### Replication Steps

* Go to [example script](https://shopatshowcase.myshopify.com/admin/apps/d25e45407e508f96409c2dd796e9bd95/scripts/24019051)
* Click `Duplicate`
* See `Failed to duplicate the script; refresh or try agin later` message

### More Information

* [Splunk Logs](https://logs.shopify.io/en-US/app/search/search?q=search%202334d47d-9a33-4e06-a01e-facfe34e32c0&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=1565100311&latest=1565101211&sid=1565101280.87361_6376F8BF-5E5C-4E4C-9BF8-1E079BB8768F) show 422 error but not much else from what I can see

Error shows for every script I tested on the merchants store
I can't replicate the error on my test store with existing scripts or when I copy the merchants script over to my store

[Zendesk Ticket](https://shopify.zendesk.com/agent/tickets/13741017)
@Shopify/scripts

**Comment by DuncanUszkay1** [comment]
Can they create scripts?

**Comment by Rony-C** [comment]
They didn't say but I can't create one at the moment, it's taking ages to finish and I'm seeing a 404 and 422 in the console

![alt](https://screenshot.click/7fvuy_2019-08-06_.png)

**Comment by DuncanUszkay1** [comment]
I've discovered the problem- They've exceeded the limit of 100 scripts. If they delete some of theirs it should work
