### ISSUE TITLE
Scripts should run on the StoreFront API as well as other channels

### ISSUE THREAD

**Issue by amaidah** [Shopify/shopify-scripts#8]
```
Scripts are limited to the Online Store channel only:
Scripts are not supported and do not fire in the wholesale channel checkout
Scripts do not fire when used in conjunction with the Buy Button
Scripts do not fire when sending a draft order invoice to a customer
Note: Scripts DO fire if using checkout permalinks
```

Part of Shopify's appeal is the ability to leverage all the amazing OOB features that Shopify provides such as cart/checkout/order management. Yet, the inability to run Shopify Scripts on a Shopify Plus store's Storefront API channel is really misleading to how much the Storefront API can be used to create a complex custom storefront experience.

Why do the Shopify Scripts only run on the cart object?
Since the Storefront API skips the creation of a cart object and creates a checkout object, why can't Shopify allow the scripts to run on the checkout object for all channels besides the Online Store channel? 

I would love to be able to leverage Shopify to its full capabilities.

**Comment by Alex1sz** [comment]
+1

**Comment by yaniiv** [comment]
This is a huge deal! +1

**Comment by rmaung** [comment]
+1

We need some more visibility and follow-up on this. The draw of Shopify Plus was for us to have finer control over the customization of our store, in addition to the complex products that we offer and sell.

Had we known of such limitations existing even on Shopify Plus, it probably would have been better to create and manage our store completely from scratch.

**Comment by amitojha1** [comment]
+1

**Comment by davejcameron** [comment]
We recently announced support for Storefront API and Shopify Scripts, you can read more about this here: https://developers.shopify.com/changelog/storefront-api-updates-metafields-scripts-and-more

**Comment by byjpr** [comment]
Thanks for updating everyone @davejcameron. I'm closing out the issue. 👍

**Comment by Eurotimmy** [comment]
Hi all... the URL above from @davejcameron and also the link from within the 'Shopify Scripts' app gives me a 404.
(is it just me?)

**Comment by dumle11** [comment]
The link has changed since: https://shopify.dev/changelog/storefront-api-updates-metafields-scripts-and-more
