### ISSUE TITLE
Scripts not saving or running 2nd time Error, Failed to run script... is shown

### ISSUE THREAD

**Issue by keithbrosnan** [Shopify/shopify-scripts#9]
### Problem

A script error is appearing when running a script twice: "Failed to run the script; refresh or try again later"

![](https://screenshot.click/21-35-yezkd-vvzho.jpg)

### Scope

Identified on 2 stores

### Examples

https://shinesty.myshopify.com/admin/apps/d25e45407e508f96409c2dd796e9bd95/scripts/6848527

https://shinesty.myshopify.com/admin/apps/d25e45407e508f96409c2dd796e9bd95/scripts/46923845

Screencast:
https://www.loom.com/share/25a6d9c71c214805a22c8fc306f56900

#### Expected vs Actual

Expected: Should save and run without error
Actual: Save shows error, 2nd run script also shows error. (workaround steps at bottom)

### Replication Steps

1. Adding a product to the cart input
2. Clicking "Run Script"
3. Clicking "Run Script" again will show the error above

This happens even on a script with nothing except `Output.cart = Input.cart` in the code

### More Information

Workaround for now is:

```When adding a product to the cart input, save the script first. Once it's saved, running the script multiple times will work```

[Zendesk ticket 1](https://shopify.zendesk.com/agent/tickets/12996785)
[Zendesk ticket 2](https://shopify.zendesk.com/agent/tickets/12973921)

@Shopify/scripts

**Comment by ErinRenNumber1** [comment]
I tophatted in my dev shop and seems to be fixed.
